#!/bin/bash

set -e
set -x

container=unpriv

if [ "$(lxc list host1:$container | grep -c "\<$container\>")" -eq "0" ]; then
  source=host2
  dest=host1
else
  source=host1
  dest=host2
fi

# if just testing plumbing (i.e. whether checkpoint/restore works), it can be
# useful to unset the base image so that the target LXD doesn't extract first
# lxc config unset $container volatile.base_image

if [ "$(lxc list $source: | grep "\<$container\>" | grep -ci RUNNING)" -eq "0" ]; then
  lxc start $source:$container
  sleep 2
fi

time lxc move $source:$container $dest:$container
