#!/bin/bash

host=$1
if [ -z "$1" ]; then
  host=dev.local
fi

# explicitly don't use set -e here, because all of these can fail and we don't
# care.
set -x

for container in $(ssh $host lxc list --force-local | tail -n+3 | grep "^| " | cut -d' ' -f2); do
	ssh $host lxc delete "${container}" --force-local -f || true
done

ssh $host lxc network delete lxdbr0

ssh $host sudo killall lxd
ssh $host sudo zpool destroy -f lxd
ssh $host sudo vgremove -f lxd
ssh $host sudo rm -rf /var/lib/lxd

ssh $host sudo rm -rf /tmp/lxd.lvm
