#!/bin/bash

host=dev

# explicitly don't use set -e here, because all of these can fail and we don't
# care.
set -x

for container in $(ssh $host lxc list --force-local | tail -n+3 | grep "^| " | cut -d' ' -f2); do
	ssh $host lxc delete "${container}" --force-local -f || true
done

ssh $host sudo killall lxd
ssh $host sudo zpool destroy -f lxd
ssh $host sudo rm -rf /var/lib/lxd
