#!/bin/bash

set -e
set -x

container=unpriv

if [ "$(lxc list host1:$container | grep -c "\<$container\>")" -eq "0" ]; then
  source=host2
  dest=host1
else
  source=host1
  dest=host2
fi

if [ "$(lxc list $source: | grep "\<$container\>" | grep -ci RUNNING)" -eq "0" ]; then
  lxc start $source:$container
  sleep 2
fi

lxc move $source:$container $dest:$container
